spring:
  datasource:
      url: jdbc:mysql://localhost:3306/studio?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: 123123
mybatis:
   mapperLocations: classpath:/mapper/*.xml
server:
  port: 8080